export const Routes = {
  // REGISTRATION SECTION
  REGISTRATION_STEP1_SCREEN: "REGISTRATION_STEP1_SCREEN",
  REGISTRATION_STEP2_SCREEN: "REGISTRATION_STEP2_SCREEN",
  REGISTRATION_STEP3_SCREEN: "REGISTRATION_STEP3_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  CHANGE_EMAIL_SCREEN: "CHANGE_EMAIL_SCREEN",
  CHANGE_PASSWORD_SCREEN: "CHANGE_PASSWORD_SCREEN",
  LOGIN_STACK: "LOGIN_STACK",
  REGISTRATION_STACK: "REGISTRATION_STACK",
  HOME_SCREEN: "HOME_SCREEN",
  THANK_YOU_PAGE: "THANK_YOU_PAGE",
  MENU_ADMIN_SCREEN: "MENU_ADMIN_SCREEN",
  MENU_USER_SCREEN: "MENU_USER_SCREEN",
  MAIN_TAB_STACK: "MAIN_TAB_STACK",
  AUTH_STACK: "AUTH_STACK",
};
